export * from "./IPostGreFindRepository"
export * from "./IPostGreAddRepository"
export * from "./IPostGreDeleteRepository"
export * from "./IPostGreFindAllRepository"
export * from "./IPostGreFindByIdRepository"
export * from "./IPostGreUpdateRepository"
